### ISSUE TITLE
payara/server-full:5.2021.4 - Error occurred during deployment

### ISSUE THREAD

**Issue by dzabdelhak** [imixs/imixs-jsf-example#65]
i have this error when deploying the app on my payara server 5.2021.4
here is server.log 

`[2021-10-06T13:36:09.539-0400] [Payara 5.2021.4] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=655 _ThreadName=admin-thread-pool::admin-listener(23)] [timeMillis: 1633541769539] [levelValue: 1000] [[
  Exception during lifecycle processing
java.lang.AbstractMethodError: Method org/imixs/workflow/engine/ImixsConfigSource.getPropertyNames()Ljava/util/Set; is abstract
        at org.imixs.workflow.engine.ImixsConfigSource.getPropertyNames(ImixsConfigSource.java)
        at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.getPropertyNames(PayaraConfig.java:195)
        at fish.payara.microprofile.openapi.impl.config.OpenApiConfiguration.<init>(OpenApiConfiguration.java:101)
        at fish.payara.microprofile.openapi.impl.OpenAPISupplier.<init>(OpenAPISupplier.java:97)
        at fish.payara.microprofile.openapi.impl.OpenApiService.registerApp(OpenApiService.java:114)
        at fish.payara.microprofile.openapi.activation.OpenApiApplicationContainer.start(OpenApiApplicationContainer.java:59)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:293)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:364)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:580)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:272)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:240)
        at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:294)
        at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
        at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:335)
        at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.portunif.PUFilter.handleRead(PUFilter.java:208)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
]]

[2021-10-06T13:36:09.540-0400] [Payara 5.2021.4] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=655 _ThreadName=admin-thread-pool::admin-listener(23)] [timeMillis: 1633541769540] [levelValue: 1000] [[
  Exception while loading the app]]

[2021-10-06T13:36:09.622-0400] [Payara 5.2021.4] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=655 _ThreadName=admin-thread-pool::admin-listener(23)] [timeMillis: 1633541769622] [levelValue: 1000] [[
  Undeployment failed for context ]]

[2021-10-06T13:36:09.628-0400] [Payara 5.2021.4] [INFO] [] [javax.enterprise.system.container.ejb.com.sun.ejb.containers] [tid: _ThreadID=655 _ThreadName=admin-thread-pool::admin-listener(23)] [timeMillis: 1633541769628] [levelValue: 800] [[
  No timers to be deleted for id: 107055400272789504]]

[2021-10-06T13:36:09.641-0400] [Payara 5.2021.4] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=655 _ThreadName=admin-thread-pool::admin-listener(23)] [timeMillis: 1633541769641] [levelValue: 1000] [[
  Exception while loading the app : Method org/imixs/workflow/engine/ImixsConfigSource.getPropertyNames()Ljava/util/Set; is abstract]]

[2021-10-06T13:36:09.742-0400] [Payara 5.2021.4] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=652 _ThreadName=admin-thread-pool::admin-listener(20)] [timeMillis: 1633541769742] [levelValue: 800] [[
  Exception Occurred :Error occurred during deployment: Exception while loading the app : Method org/imixs/workflow/engine/ImixsConfigSource.getPropertyNames()Ljava/util/Set; is abstract. Please see server.log for more details. ]]
`

**Comment by dzabdelhak** [comment]
@rsoika

**Comment by rsoika** [comment]
Hm, can you try to upgrade the worklfow version in the pom.xml to 

    <org.imixs.workflow.version>5.2.12</org.imixs.workflow.version>


The error message is from the Microprofile Area and should not happen with the latest version of Imixs-Workflow. I have tested it currently with payara version 5.201 which is older than yours?

**Comment by dzabdelhak** [comment]
hi @rsoika  i tried to upgrade to the newer version now i get this error : 


An error has occurred during deployment: Exception while loading the app : CDI deployment failure:WELD-000163: Non-unique bean deployment identifier detected: - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-faces], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-jax-rs], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-engine], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-index-lucene], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-faces], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-engine], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example.war/WEB-INF/lib/imixs-workflow-jax-rs], - BeanDeployment [beanDeploymentArchiveId=imixs-jsf-example .... msg.seeServerLog
